export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const REGISTRATION_USER = "REGISTRATION_USER";
export const REGISTRATION_USER_START = "REGISTRATION_USER_START";
export const REGISTRATION_USER_ERROR = "REGISTRATION_USER_ERROR";
